### ISSUE TITLE
Link to corrections page

### ISSUE THREAD

**Issue by boredland** [patrickmj/Corrections#6]
Hi there,

perhaps I'm an Idiot, but where do I find the link - or the option to enable it - in the actual interface? If I enter [myurl]corrections/index/add/item_id/[id] it works quite nice.

Yours
Jonas

**Comment by patrickmj** [comment]
The link should be at the bottom of all the item pages. The text is something you configure in the plugin's config when you activate it. 

If it isn't there, then something is amiss. What theme are you using?

**Comment by boredland** [comment]
Well. I was blind! Thank you so much for this awesome plugin!

**Comment by patrickmj** [comment]
It is admittedly not styled to be particularly visible!
