### ISSUE TITLE
Omeka-S

### ISSUE THREAD

**Issue by andrisi** [patrickmj/Corrections#9]
Dear Developers, is there a plan to move/update this plugin for Omeka S? Or just update it? Does not seem to handle user added element types. This is an excellent plugin/idea in the age of Wikipedia... Thanks!

**Comment by patrickmj** [comment]
Glad you like it, but no plans for updating or porting to Omeka S. This was part of a side project from long ago that I'm no longer working on.

I should've put a license in there, but consider it wide open for any forking and work that others want to do.

**Comment by andrisi** [comment]
Thanks for getting back to me!
